# Generated by Django 2.0.3 on 2018-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('Std_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('Class', models.PositiveIntegerField()),
                ('Mobile_no', models.BigIntegerField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('Academic_year', models.PositiveIntegerField()),
                ('Branch', models.CharField(max_length=30)),
            ],
        ),
    ]
