# Generated by Django 2.0.3 on 2019-01-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190112_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generalprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=255)),
                ('password', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(default=None, max_length=255)),
                ('password', models.CharField(default=None, max_length=255)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('citizen_no', models.IntegerField(default=None)),
                ('job', models.CharField(default=None, max_length=255, null=True)),
                ('points', models.IntegerField(default=None, max_length=255)),
                ('random', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Users',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
